target 'ReadyER2' do
platform :ios, '12.0'

use_frameworks!

pod 'Firebase/Core'
pod 'Firebase'
pod 'Firebase/Database'
pod 'FirebaseUI'
pod 'FirebaseUI/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'

end
